services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "54321:5432"
      - "54321:5432"
    environment:
      POSTGRES_USER: taskem
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: taskem
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    restart: always
    ports:
      - "63798:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "token-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  smtp:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    restart: unless-stopped


  listmonk:
    image: listmonk/listmonk:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "9000:9000"
    command: [ sh, -c, "yes | ./listmonk --install --config=\"\" && ./listmonk" ]
    environment:
      LISTMONK_app__address: "0.0.0.0:9000"
      LISTMONK_app__admin_username: taskem
      LISTMONK_app__admin_password: taskem
      LISTMONK_db__host: db
      LISTMONK_db__port: 5432
      LISTMONK_db__user: taskem
      LISTMONK_db__password: taskem
      LISTMONK_db__database: taskem
      LISTMONK_db__ssl_mode: disable

  #  redis:
  #    image: redis
  #    restart: always
  #    ports:
  #      - 63798:6379
  #    healthcheck:
  #      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 5

  #  minio:
  #    image: quay.io/minio/minio
  #    restart: always
  #    command: server /data --console-address ":9001"
  #    ports:
  #      - "12200:9000"
  #      - "9001:9001"
  #    environment:
  #      MINIO_ROOT_USER: root
  #      MINIO_ROOT_PASSWORD: YOUR_PASSWORD
  #      MINIO_DOMAIN: minio
  #    networks:
  #      default:
  #        aliases:
  #          - users.minio
  #          - teams.minio

  rabbitmq:
    image: rabbitmq:3.13.6-management
    environment:
      RABBITMQ_DEFAULT_USER: taskem
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "56721:5672"
      - "8080:15672"

  server:
    env_file: .env.dev
    build:
      context: ./apps/server/
      target: final
    depends_on:
      - db
      - redis
    ports:
      - "50051:50051"

#  notification:
#    env_file: ".env"
#    build:
#      context: ./apps/server/
#      target: final
#    depends_on:
#      - db
#    ports:
#      - 50051:50051

volumes:
  db-data:
  redis-data:
    driver: local