services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: taskem
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: taskem
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  redis:
#    image: redis
#    restart: always
#    ports:
#      - 63798:6379
#    healthcheck:
#      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

#  minio:
#    image: quay.io/minio/minio
#    restart: always
#    command: server /data --console-address ":9001"
#    ports:
#      - "12200:9000"
#      - "9001:9001"
#    environment:
#      MINIO_ROOT_USER: root
#      MINIO_ROOT_PASSWORD: YOUR_PASSWORD
#      MINIO_DOMAIN: minio
#    networks:
#      default:
#        aliases:
#          - users.minio
#          - teams.minio

#  server:
#    restart: always
#    build:
#      context: .
#    depends_on:
#      - db
#      - minio
#      - redis
#    ports:
#      - 50051:50051
#      - 9600:9090
#      - 3000:3000

volumes:
  db-data: