services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: taskem
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: taskem
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    restart: always
    ports:
      - "63798:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "token-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    env_file: ".env"
    build:
      context: .
      target: final
    depends_on:
      - db
      - redis
    ports:
      - "50051:50051"

volumes:
  db-data:
  redis-data:
    driver: local