name: Test and coverage

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - module: ./apps/server
            name: server
          - module: ./apps/notification
            name: notification
          - module: ./libs/queue
            name: queue
          - module: ./libs/template
            name: template

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./${{ matrix.module }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ matrix.module }}/coverage.out
          flags: ${{ matrix.module }}
